---
- name: Check logstash access information
  fail:
    msg: Undefined variables logstash_host and logstash_port
  when: logstash_host is undefined or logstash_port is undefined
  
- name: Check log_list
  fail:
    msg: Undefined variables log_list
  when: log_list is undefined
