---
- name: check unsupported system
  fail:
    msg: "Not supported {{ ansible_system }}"
  when: ansible_system != 'Linux'

# check ubuntu
- name: check distribution
  fail:
    msg: "Not supported {{ ansible_distribution }}"
  when: ansible_distribution not in ['Ubuntu', 'CentOS']

# check ubuntu 16.04
- name: check ubuntu version
  fail:
    msg: "Not supported {{ ansible_distribution }} {{ ansible_distribution_version }}"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version not in ['12.04', '14.04', '16.04']

# check centos 7
- name: check centos version
  fail:
    msg: "Not supported {{ ansible_distribution }} {{ ansible_distribution_version }}"
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version != '7'
