---
- name: Check logstash access information
  fail:
    msg: Undefined variables logstash_host and logstash_port
  when: logstash_host is undefined or logstash_port is undefined
  
- name: Check prospectors
  fail:
    msg: Undefined variables prospectors
  when: prospectors is undefined
