---
- name: Install java8 on centos
  yum:
    name: java-1.8.0-openjdk
    update_cache: yes

- name: Add gpg-key on centos
  rpm_key:
    key: https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Add repository on centos
  yum_repository:
    name: 'elastic-{{ version }}'
    description: 'Elastic repository for {{ version }} packages'
    baseurl: 'https://artifacts.elastic.co/packages/{{ version }}/yum'
    gpgcheck: yes
    gpgkey : https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes

- name: Install filebeat on centos
  yum:
    name: filebeat
    update_cache: yes
