---
- include: check_system.yml
- include: check_variables.yml

- include: install_filebeat_ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include: install_filebeat_centos.yml
  when: ansible_distribution == 'CentOS'

- name: Get a short hostname
  shell: hostname -s
  register: hostname_short

- name: Register filebeat_name variable using a short hostname
  set_fact: filebeat_name="{{ hostname_short.stdout | lower }}"

- name: Replace filebeat.yml
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    mode: 0644

- name: Start services
  systemd:
    daemon_reload: yes
    name: filebeat
    enabled: yes
    state: restarted
